name: Build and Push Multi-Architecture Image

on:
  workflow_dispatch:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: elioseverojunior/github-tests
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=all_images
          # Build arguments for your application, if needed
          # build-args: |
          #   BUILD_VERSION=${{ steps.meta.outputs.version }}

      - name: Create manifest
        id: manifest
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          load: true
          # This will produce 'latest', 'v1.0.0', etc. tags
          tags: ${{ steps.meta.outputs.tags }}
          # Specify images built for each architecture
          images: |
            ${{ steps.build-push.outputs.all_images }}
